language: python

python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  - DEPS="Django>=1.8,<1.9"
  - DEPS="Django>=1.9,<1.10"
  - DEPS="Django>=1.10,<1.11"
  - DEPS="Django>=1.11,<1.12"
  - DEPS="Django>=2.0,<2.1"
  - DEPS="Django>=2.1,<2.2"

install:
  - pip install pipenv codecov
  - pipenv install --dev
  - pipenv run pip install -e .
  - pipenv run pip install $DEPS

script: pipenv run py.test --cov

after_success:
  - codecov
