[tool.black]
target-version = ['py35', 'py36', 'py37', 'py38']
exclude = '(/migrations/)'
line-length = 96
skip-string-normalization = true
skip-numeric-underscore-normalization = true

[tool.isort]
known_first_party = ['didadata']
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
default_section = 'THIRDPARTY'
skip_glob = ['**/migrations/**']
line_length = 96
use_parantheses = true
include_trailing_comma = true
multi_line_output = 3
